'use strict';

const canvas = document.querySelector('#game');
const ctx = canvas.getContext('2d');
const shell = document.querySelector('#game-shell');
const $ = s => document.querySelector(s);
const ui = {
  hud: $('#hud'), start: $('#start-screen'), guide: $('#guide-screen'), upgrades: $('#upgrade-screen'), cards: $('#upgrade-cards'),
  pause: $('#pause-screen'), end: $('#end-screen'), hp: $('#hp-bar'), hpText: $('#hp-text'), xp: $('#xp-bar'),
  timer: $('#timer'), kills: $('#kills'), level: $('#level'), weapon: $('#weapon-status'), phase: $('#phase-status'), bossHud: $('#boss-hud'), bossBar: $('#boss-bar')
};

let W=0,H=0,dpr=1,last=0,state='menu',elapsed=0,spawnClock=0,shake=0,flash=0,selectedWeapon='pulse',bossSpawned=false,lastWin=null;
let player,enemies=[],bullets=[],enemyBullets=[],beams=[],gems=[],particles=[],texts=[],keys={},stars=[];
const touch={active:false,id:null,x:0,y:0,startX:0,startY:0};
const TAU=Math.PI*2, XP_MULTIPLIER=1.15, GAME_VERSION='0.9.0-test.6', rand=(a,b)=>a+Math.random()*(b-a), clamp=(v,a,b)=>Math.max(a,Math.min(b,v));

function resize(){dpr=Math.min(devicePixelRatio||1,2);const rect=shell.getBoundingClientRect();W=rect.width||Math.min(innerWidth,768);H=rect.height||innerHeight;canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);if(!stars.length)stars=Array.from({length:120},()=>({x:Math.random(),y:Math.random(),s:rand(.3,1.8),a:rand(.15,.7)}));const sideways=matchMedia('(pointer:coarse) and (orientation:landscape)').matches;if(sideways&&state==='playing')state='orientation';else if(!sideways&&state==='orientation'){state='playing';last=performance.now()}}
addEventListener('resize',resize);resize();

const weaponNames={pulse:'脈衝砲',chain:'連鎖雷電'};
function freshPlayer(){return{x:W/2,y:H/2,r:12,speed:199.75,hp:100,maxHp:100,damage:18,fireRate:.5,fireClock:0,bulletSpeed:520,projectileScale:1,pierce:0,multishot:1,armor:0,regen:0,critChance:.05,critDamage:1.75,dodge:0,chainRange:185,effectRange:1,phaseCooldown:0,phaseActive:false,level:1,xp:0,nextXp:7,invuln:0,angle:0,weapon:selectedWeapon,weaponLevel:1,evolved:false,skillLevels:{}};}
function startGame(){player=freshPlayer();enemies=[];bullets=[];enemyBullets=[];beams=[];gems=[];particles=[];texts=[];elapsed=spawnClock=0;shake=flash=0;bossSpawned=false;state='playing';ui.kills.textContent='0';ui.timer.textContent='06:00';ui.bossBar.style.width='100%';ui.bossHud.classList.add('hidden');ui.start.classList.add('hidden');ui.guide.classList.add('hidden');ui.end.classList.add('hidden');ui.pause.classList.add('hidden');ui.upgrades.classList.add('hidden');ui.hud.classList.remove('hidden');setMusic('battle');updateUI();beep(330,.08,'sine',.04);}

const skills=[
 {id:'damage',icon:'✦',name:'過載核心',desc:'武器傷害提高 15%。',color:'#ff6d8d',apply:p=>p.damage*=1.15},
 {id:'haste',icon:'⌁',name:'脈衝加速',desc:'攻擊間隔縮短 12%。',color:'#69f5ff',apply:p=>p.fireRate*=.88},
 {id:'armor',icon:'◇',name:'相位裝甲',desc:'受到的傷害減少 8%。',color:'#7db6ff',apply:p=>p.armor=Math.min(.4,p.armor+.08)},
 {id:'vitality',icon:'♥',name:'奈米修復',desc:'最大生命提高 20，並恢復 30 生命。',color:'#ff688b',apply:p=>{p.maxHp+=20;p.hp=Math.min(p.maxHp,p.hp+30)}},
 {id:'regen',icon:'✚',name:'自癒裝甲',desc:'每秒恢復 1 生命。',color:'#66f0a7',apply:p=>p.regen+=1},
 {id:'critical',icon:'※',name:'弱點解析',desc:'暴擊機率提高 8%。',color:'#ffcf63',apply:p=>p.critChance+=.08},
 {id:'dodge',icon:'◈',name:'幻影迴避',desc:'獲得 5% 機率完全閃避傷害。',color:'#8da7ff',apply:p=>p.dodge+=.05},
 {id:'emergency',icon:'⬡',name:'緊急相位',desc:'受傷後觸發無敵，每級增加 0.5 秒；冷卻 15 秒。',color:'#70ffe1',apply:p=>{}}
];
function skillUpgrade(skill){const current=player.skillLevels[skill.id]||0,next=current+1;return{...skill,tag:`LV.${current} → LV.${next}`,apply:p=>{p.skillLevels[skill.id]=next;skill.apply(p)}}}
function shuffle(items){for(let i=items.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[items[i],items[j]]=[items[j],items[i]]}return items}
function offerUpgrade(){state='upgrade';resetTouch();ui.upgrades.classList.remove('hidden');const picks=shuffle(skills.filter(s=>(player.skillLevels[s.id]||0)<5).map(skillUpgrade)).slice(0,3);ui.cards.innerHTML='';picks.forEach(u=>{const b=document.createElement('button');let chosen=false;b.className='card';b.style.setProperty('--card-color',u.color);b.innerHTML=`<span class="icon">${u.icon}</span><h3>${u.name}</h3><p>${u.desc}</p><small>${u.tag}</small>`;const choose=()=>{if(chosen)return;chosen=true;u.apply(player);player.invuln=2;ui.upgrades.classList.add('hidden');state='playing';beep(660,.12,'triangle',.06);updateUI()};b.onclick=choose;b.addEventListener('pointerdown',e=>{if(e.pointerType!=='mouse'){e.preventDefault();choose()}});ui.cards.appendChild(b)});}

function edgePosition(margin=50){const side=Math.floor(Math.random()*4);if(side===0)return{x:rand(0,W),y:-margin};if(side===1)return{x:W+margin,y:rand(0,H)};if(side===2)return{x:rand(0,W),y:H+margin};return{x:-margin,y:rand(0,H)}}
function spawnEnemy(){const{x,y}=edgePosition(),roll=Math.random();let t,mobRoll=roll;if(elapsed>150&&roll<.1)t='dasher';else{if(elapsed>150)mobRoll=(roll-.1)/.9;t=elapsed>115&&mobRoll<.13?'splitter':elapsed>70&&mobRoll<.27?'shooter':elapsed>95&&mobRoll<.47?'tank':elapsed>30&&mobRoll<.7?'swift':'drone'}
 const data=t==='dasher'?{r:11.2,hp:140,speed:64,damage:20,xp:4,color:'#ff3856'}:t==='splitter'?{r:16.8,hp:115,speed:58,damage:18,xp:5,color:'#60e8a5'}:t==='shooter'?{r:12,hp:70,speed:55,damage:13,xp:3,color:'#64a8ff'}:t==='tank'?{r:20,hp:140,speed:45,damage:22,xp:4,color:'#a879ff'}:t==='swift'?{r:8.8,hp:40,speed:128,damage:12,xp:2,color:'#ffb65c'}:{r:12.8,hp:50,speed:70,damage:14,xp:1,color:'#ff5d82'};
 const elite=elapsed>70&&Math.random()<Math.min(.16,.035+elapsed/2400);if(elite){data.r*=1.24;data.hp*=2.6;data.speed*=1.12;data.damage*=1.55;data.xp*=3}
 enemies.push({x,y,type:t,elite,hit:0,dead:false,shotClock:rand(.6,1.8),dashState:'chase',dashClock:t==='dasher'?rand(2.5,4.5):0,dashMax:t==='dasher'?260:0,dashSpeed:t==='dasher'?520:0,...data,maxHp:data.hp});}
function spawnBoss(){const{x,y}=edgePosition(90),hp=5000;bossSpawned=true;enemies=[];enemyBullets=[];setMusic('boss');enemies.push({x,y,type:'boss',elite:false,boss:true,phase:1,attackClock:3,specialState:'idle',specialIndex:0,summonClock:10,dashState:'chase',dashClock:6,dashMax:360,dashSpeed:650,r:46.4,hp,maxHp:hp,speed:36,damage:30,xp:30,color:'#d15cff',hit:0,dead:false});ui.bossHud.classList.remove('hidden');shake=18;flash=.35;beep(48,.8,'sawtooth',.1)}
function summonBossElites(e){const offset=rand(0,TAU);for(let i=0;i<2;i++){const a=offset+i*Math.PI,d=rand(70,105),x=clamp(e.x+Math.cos(a)*d,20,W-20),y=clamp(e.y+Math.sin(a)*d,80,H-20),hp=180;enemies.push({x,y,type:'drone',elite:true,r:16,hp,maxHp:hp,speed:88,damage:20,xp:6,color:'#ffe06e',hit:0,dead:false})}texts.push({x:e.x,y:e.y-e.r-25,text:'菁英增援',life:1.2,big:true});burst(e.x,e.y,'#ffe06e',24);beep(95,.3,'sawtooth',.06)}
function nearestEnemy(x,y,excluded=new Set(),range=Infinity){let target=null,best=range*range;for(const e of enemies){if(e.dead||excluded.has(e))continue;const d=(e.x-x)**2+(e.y-y)**2;if(d<best){best=d;target=e}}return target}
function firePulse(){const target=nearestEnemy(player.x,player.y);if(!target)return;const base=Math.atan2(target.y-player.y,target.x-player.x),count=player.multishot+(player.evolved?2:0);player.angle=base;for(let i=0;i<count;i++){const spread=(i-(count-1)/2)*.14,a=base+spread;bullets.push({x:player.x+Math.cos(a)*20,y:player.y+Math.sin(a)*20,vx:Math.cos(a)*player.bulletSpeed,vy:Math.sin(a)*player.bulletSpeed,r:(player.evolved?6:4)*player.projectileScale,life:1.3,hits:player.pierce+1+(player.evolved?1:0),explosive:player.evolved});}beep(190,.025,'square',.012)}
function fireChain(){let target=nearestEnemy(player.x,player.y);if(!target)return;let x=player.x,y=player.y,damage=player.damage*1.15;const hit=new Set(),jumps=1+Math.ceil(player.weaponLevel/2)+(player.evolved?2:0);player.angle=Math.atan2(target.y-y,target.x-x);for(let i=0;i<jumps&&target;i++){beams.push({x1:x,y1:y,x2:target.x,y2:target.y,life:.16});hit.add(target);dealDamage(target,damage);x=target.x;y=target.y;damage*=.84;target=nearestEnemy(x,y,hit,player.chainRange*(player.evolved?1.2:1))}beep(520,.08,'sawtooth',.025)}
function fire(){if(player.weapon==='pulse')firePulse();else if(player.weapon==='chain')fireChain()}
function burst(x,y,color,n=8){for(let i=0;i<n;i++){const a=rand(0,TAU),s=rand(30,170);particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:rand(.2,.7),max:1,color,size:rand(1,4)})}}
function damageEnemy(e,d,critical=false){e.hp-=d;e.hit=.08;texts.push({x:e.x,y:e.y-e.r-5,text:critical?`✦ ${Math.round(d)}`:Math.round(d),life:critical?.7:.45,critical});if(e.boss)ui.bossBar.style.width=`${Math.max(0,e.hp/e.maxHp*100)}%`;if(e.hp<=0&&!e.dead){e.dead=true;ui.kills.textContent=+ui.kills.textContent+1;burst(e.x,e.y,e.color,e.boss?60:e.elite?24:12);gems.push({x:e.x,y:e.y,r:e.xp>2?7:5,value:e.xp,bob:rand(0,TAU)});if(e.type==='splitter')for(let i=0;i<2;i++){const hp=32;enemies.push({x:e.x+rand(-15,15),y:e.y+rand(-15,15),type:'swarm',elite:false,r:6.4,hp,maxHp:hp,speed:145,damage:8,xp:1,color:'#8dffc5',hit:0,dead:false})}if(e.boss)shake=24;beep(e.boss?45:e.type==='tank'?70:100,e.boss?.5:.05,'sawtooth',e.boss?.1:.025);if(e.boss){ui.bossHud.classList.add('hidden');endGame(true)}}}
function dealDamage(e,d){const critical=Math.random()<player.critChance;damageEnemy(e,d*(critical?player.critDamage:1),critical)}
function advanceWeapon(){if([3,5,7,9].includes(player.level)&&player.weaponLevel<5){player.weaponLevel++;player.damage*=1.14;if(player.weapon==='pulse'){player.fireRate*=.92;player.bulletSpeed*=1.12;player.projectileScale*=1.08;if([5,9].includes(player.level))player.multishot++}else{player.fireRate*=.94;player.chainRange*=1.08}texts.push({x:player.x,y:player.y-34,text:`${weaponNames[player.weapon]} LV.${player.weaponLevel}`,life:1.2,big:true});burst(player.x,player.y,'#ffe676',22);flash=.15;beep(720,.18,'triangle',.06)}if(player.level>=11&&!player.evolved){player.evolved=true;if(player.weapon==='pulse')player.effectRange*=1.35;const evolvedName=player.weapon==='pulse'?'星爆加農':'神罰雷網';texts.push({x:player.x,y:player.y-34,text:`進化・${evolvedName}`,life:1.5,big:true});burst(player.x,player.y,'#fff19a',45);flash=.35;beep(880,.35,'triangle',.08)}}
function gainXp(n){player.xp+=n*XP_MULTIPLIER;while(player.xp>=player.nextXp){player.xp-=player.nextXp;player.level++;player.nextXp=Math.floor(player.nextXp*1.34+3);advanceWeapon();updateUI();offerUpgrade();break}updateUI();}
function enemyShot(x,y,a,speed=150,damage=12,r=5,color='#ff334f'){enemyBullets.push({x,y,vx:Math.cos(a)*speed,vy:Math.sin(a)*speed,damage,r,color,life:6})}
function radialShot(e,count,speed,damage){for(let i=0;i<count;i++)enemyShot(e.x,e.y,i*TAU/count+elapsed*.25,speed,damage,5,'#ff2948')}
function dashPathLength(e,a){const c=Math.cos(a),s=Math.sin(a);let length=e.dashMax;if(c>0)length=Math.min(length,(W-e.r-e.x)/c);else if(c<0)length=Math.min(length,(e.x-e.r)/-c);if(s>0)length=Math.min(length,(H-e.r-e.y)/s);else if(s<0)length=Math.min(length,(e.y-e.r-72)/-s);return Math.max(0,length)}
function updateDash(e,dt,a){if(e.dashState==='windup'){e.dashTimer-=dt;if(e.dashTimer<=0){e.dashState='dashing';e.dashRemaining=e.dashLength;beep(e.boss?70:120,.16,'sawtooth',.06)}return true}if(e.dashState==='dashing'){const step=Math.min(e.dashRemaining,e.dashSpeed*dt);e.x+=Math.cos(e.dashAngle)*step;e.y+=Math.sin(e.dashAngle)*step;e.dashRemaining-=step;if(e.dashRemaining<=0){e.dashState='recover';e.dashTimer=e.boss?.75:.55;e.dashClock=e.boss?8:rand(6,9)}return true}if(e.dashState==='recover'){e.dashTimer-=dt;if(e.dashTimer<=0)e.dashState='chase';return true}e.dashClock-=dt;if(e.dashClock<=0){e.dashState='windup';e.dashTimer=e.boss?2:1.5;e.dashAngle=a;e.dashLength=dashPathLength(e,a);texts.push({x:e.x,y:e.y-e.r-18,text:'DASH',life:.8,critical:true});beep(e.boss?105:165,.18,'square',.04);return true}return false}
function pointSegmentDistance(px,py,x1,y1,x2,y2){const dx=x2-x1,dy=y2-y1,l2=dx*dx+dy*dy;if(!l2)return Math.hypot(px-x1,py-y1);const t=clamp(((px-x1)*dx+(py-y1)*dy)/l2,0,1);return Math.hypot(px-(x1+t*dx),py-(y1+t*dy))}
function finishBossSpecial(e){e.specialState='idle';e.attackClock=e.phase===3?1:e.phase===2?1.5:1.25}
function beginBossSpecial(e){e.specialType=e.phase===1?'rapid':e.specialIndex++%2===0?'barrage':'rapid';e.specialState='windup';e.specialTimer=2;texts.push({x:e.x,y:e.y-e.r-25,text:e.specialType==='barrage'?'彈幕充能':'連射充能',life:1.2,big:true});beep(e.specialType==='barrage'?135:210,.3,'triangle',.055)}
function updateBossSpecial(e,dt){if(e.specialState==='windup'){e.specialTimer-=dt;if(e.specialTimer<=0){flash=.12;burst(e.x,e.y,e.specialType==='barrage'?'#ff5b9f':'#ffcf63',28);if(e.specialType==='barrage'){radialShot(e,e.phase===2?12:16,e.phase===2?155:205,e.phase===2?15:18);finishBossSpecial(e)}else{e.specialState='rapid';e.rapidShots=e.phase===1?3:e.phase===2?5:7;e.rapidClock=0}}return true}if(e.specialState==='rapid'){e.rapidClock-=dt;if(e.rapidClock<=0){const a=Math.atan2(player.y-e.y,player.x-e.x),speed=e.phase===3?260:e.phase===2?210:195,damage=e.phase===3?20:e.phase===2?17:16,r=e.phase===1?7:6;enemyShot(e.x,e.y,a,speed,damage,r,'#ff475d');e.rapidShots--;e.rapidClock=.13;beep(90,.05,'sawtooth',.025);if(e.rapidShots<=0)finishBossSpecial(e)}return true}return false}
function hurtPlayer(damage){if(player.invuln>0)return;if(Math.random()<player.dodge){player.invuln=.35;texts.push({x:player.x,y:player.y-24,text:'MISS',life:.6,critical:true});return}const lost=damage*(1-player.armor),phaseLevel=player.skillLevels.emergency||0;player.hp-=lost;if(phaseLevel>0&&player.phaseCooldown<=0){player.invuln=1+(phaseLevel-1)*.5;player.phaseActive=true;texts.push({x:player.x,y:player.y-45,text:'EMERGENCY PHASE',life:1,big:true});beep(760,.18,'sine',.06)}else player.invuln=.62;texts.push({x:player.x,y:player.y-26,text:`-${Math.round(lost)}`,life:.75,playerDamage:true});shake=12;flash=.18;burst(player.x,player.y,'#ff547d',16);updateUI();beep(55,.14,'sawtooth',.08);if(player.hp<=0)endGame(false)}
function bossPhase(e,phase){e.phase=phase;flash=.3;shake=15;enemyBullets=[];texts.push({x:e.x,y:e.y-e.r-25,text:`PHASE ${['I','II','III'][phase-1]}`,life:1.2,big:true});burst(e.x,e.y,'#db72ff',30);beep(65,.45,'sawtooth',.08)}
function updateEnemy(e,dt){e.hit=Math.max(0,e.hit-dt);const oldX=e.x,oldY=e.y,a=Math.atan2(player.y-e.y,player.x-e.x),dist=Math.hypot(player.x-e.x,player.y-e.y);if(e.boss){const ratio=e.hp/e.maxHp,targetPhase=ratio<=.33?3:ratio<=.66?2:1;if(targetPhase>e.phase)bossPhase(e,targetPhase);e.summonClock-=dt;if(e.summonClock<=0){summonBossElites(e);e.summonClock+=10}const specialBusy=updateBossSpecial(e,dt),dashBusy=!specialBusy&&updateDash(e,dt,a);if(!specialBusy&&!dashBusy){e.attackClock-=dt;if(e.attackClock<=0)beginBossSpecial(e);else{e.x+=Math.cos(a)*e.speed*dt;e.y+=Math.sin(a)*e.speed*dt}}}else if(e.type==='dasher'){if(!updateDash(e,dt,a)){e.x+=Math.cos(a)*e.speed*dt;e.y+=Math.sin(a)*e.speed*dt}}else if(e.type==='shooter'){const dir=dist>245?1:dist<175?-1:0;e.x+=Math.cos(a)*e.speed*dir*dt;e.y+=Math.sin(a)*e.speed*dir*dt;e.shotClock-=dt;if(e.shotClock<=0){enemyShot(e.x,e.y,a,190,e.damage,5,'#e5223f');e.shotClock=e.elite?1.15:1.8}}else{e.x+=Math.cos(a)*e.speed*dt;e.y+=Math.sin(a)*e.speed*dt}if(pointSegmentDistance(player.x,player.y,oldX,oldY,e.x,e.y)<player.r+e.r)hurtPlayer(e.damage)}

function update(dt){if(state!=='playing')return;elapsed+=dt;const hadInvuln=player.invuln>0;player.invuln=Math.max(0,player.invuln-dt);if(player.phaseActive&&hadInvuln&&player.invuln<=0){player.phaseActive=false;player.phaseCooldown=15}else if(!player.phaseActive&&player.phaseCooldown>0)player.phaseCooldown=Math.max(0,player.phaseCooldown-dt);player.fireClock-=dt;player.hp=Math.min(player.maxHp,player.hp+player.regen*dt);if(player.regen>0){ui.hp.style.width=`${player.hp/player.maxHp*100}%`;ui.hpText.textContent=`${Math.ceil(player.hp)} / ${player.maxHp}`}updatePhaseUI();shake*=Math.pow(.02,dt);flash=Math.max(0,flash-dt);
 let dx=(keys.ArrowRight||keys.KeyD?1:0)-(keys.ArrowLeft||keys.KeyA?1:0),dy=(keys.ArrowDown||keys.KeyS?1:0)-(keys.ArrowUp||keys.KeyW?1:0);if(touch.active){dx=touch.x;dy=touch.y}const len=Math.max(1,Math.hypot(dx,dy));player.x=clamp(player.x+dx/len*player.speed*dt,20,W-20);player.y=clamp(player.y+dy/len*player.speed*dt,72,H-22);
 if(!bossSpawned){spawnClock-=dt;const interval=Math.max(.18,.86-elapsed*.0018);if(spawnClock<=0){spawnEnemy();spawnClock=interval;if(elapsed>100&&Math.random()<elapsed/800)spawnEnemy()}if(elapsed>=360)spawnBoss()}
 if(player.fireClock<=0){fire();player.fireClock=player.weapon==='chain'?player.fireRate*1.65:player.fireRate}
 for(const b of bullets){b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;for(const e of enemies){if(e.dead||e._hit===b)continue;if(Math.hypot(b.x-e.x,b.y-e.y)<b.r+e.r){e._hit=b;dealDamage(e,player.damage);b.hits--;burst(b.x,b.y,'#75f6ff',3);if(b.explosive){for(const other of enemies)if(other!==e&&!other.dead&&Math.hypot(b.x-other.x,b.y-other.y)<58*player.effectRange)dealDamage(other,player.damage*.48);b.hits=0;burst(b.x,b.y,'#8cfaff',14)}if(b.hits<=0){b.life=0;break}}}}
 for(const e of enemies){if(!e.dead)updateEnemy(e,dt)}
 for(const b of enemyBullets){b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;if(Math.hypot(b.x-player.x,b.y-player.y)<b.r+player.r){b.life=0;hurtPlayer(b.damage)}}
 for(const g of gems){g.bob+=dt*4;const d=Math.hypot(player.x-g.x,player.y-g.y),a=Math.atan2(player.y-g.y,player.x-g.x),s=260+Math.min(700,d*1.5);g.x+=Math.cos(a)*s*dt;g.y+=Math.sin(a)*s*dt;if(d<player.r+g.r+8){g.dead=true;gainXp(g.value);beep(470,.035,'sine',.018)}}
 for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.95;p.vy*=.95;p.life-=dt}for(const t of texts){t.y-=24*dt;t.life-=dt}for(const b of beams)b.life-=dt;
 bullets=bullets.filter(b=>b.life>0&&b.x>-50&&b.x<W+50&&b.y>-50&&b.y<H+50);enemyBullets=enemyBullets.filter(b=>b.life>0&&b.x>-80&&b.x<W+80&&b.y>-80&&b.y<H+80);beams=beams.filter(b=>b.life>0);enemies=enemies.filter(e=>!e.dead);gems=gems.filter(g=>!g.dead);particles=particles.filter(p=>p.life>0);texts=texts.filter(t=>t.life>0);
 ui.timer.textContent=bossSpawned?'BOSS':formatTime(360-elapsed);
}
function updateUI(){ui.hp.style.width=`${Math.max(0,player.hp/player.maxHp*100)}%`;ui.hpText.textContent=`${Math.ceil(Math.max(0,player.hp))} / ${player.maxHp}`;ui.xp.style.width=`${player.xp/player.nextXp*100}%`;ui.level.textContent=player.level;ui.weapon.textContent=player.evolved?`${weaponNames[player.weapon]}・進化`:`${weaponNames[player.weapon]}・${['I','II','III','IV','V'][Math.min(4,player.weaponLevel-1)]}`;}
function updatePhaseUI(){const level=player.skillLevels.emergency||0;ui.phase.classList.toggle('hidden',level===0);ui.phase.classList.toggle('active',player.phaseActive);ui.phase.classList.toggle('cooldown',!player.phaseActive&&player.phaseCooldown>0);ui.phase.textContent=player.phaseActive?'緊急相位・無敵':player.phaseCooldown>0?`緊急相位・${Math.ceil(player.phaseCooldown)}s`:'緊急相位・就緒'}
function formatTime(s){s=Math.max(0,Math.ceil(s));return`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function endGame(win){if(state==='end')return;state='end';lastWin=win;resetTouch();setMusic(win?'victory':'menu');ui.bossHud.classList.add('hidden');ui.end.classList.remove('hidden');$('#end-label').textContent=win?'TARGET DESTROYED':'SIGNAL LOST';$('#end-title').textContent=win?'霸主殞落':'星火熄滅';$('#end-copy').textContent=win?'裂界霸主已被消滅，這片星域暫時恢復寧靜。':'星域吞沒了訊號，但下一次航行會走得更遠。';$('#result-time').textContent=formatTime(elapsed);$('#result-kills').textContent=ui.kills.textContent;$('#result-level').textContent=player.level;beep(win?740:90,.5,win?'triangle':'sawtooth',.08)}
function buildTestReport(){const chosen=Object.entries(player.skillLevels).filter(([,level])=>level>0).map(([id,level])=>`${skills.find(skill=>skill.id===id)?.name||id} Lv.${level}`).join('、')||'無';return[`星燼倖存者測試報告 v${GAME_VERSION}`,`結果：${lastWin?'勝利':'失敗'}`,`武器：${weaponNames[player.weapon]}${player.evolved?'（已進化）':''}`,`遊玩時間：${formatTime(elapsed)}`,`最終等級：${player.level}`,`擊破數：${ui.kills.textContent}`,`剩餘生命：${Math.ceil(Math.max(0,player.hp))} / ${player.maxHp}`,`技能：${chosen}`,`裝置：${innerWidth}×${innerHeight} / ${navigator.userAgent}`].join('\n')}
async function copyTestReport(){const report=buildTestReport(),button=$('#copy-report');try{await navigator.clipboard.writeText(report);button.textContent='已複製測試報告';setTimeout(()=>button.textContent='複製測試報告',1800)}catch{prompt('請複製以下測試報告',report)}}
function goHome(){state='menu';resetTouch();player=null;enemies=[];bullets=[];enemyBullets=[];beams=[];gems=[];particles=[];texts=[];setMusic('menu');ui.pause.classList.add('hidden');ui.end.classList.add('hidden');ui.guide.classList.add('hidden');ui.upgrades.classList.add('hidden');ui.bossHud.classList.add('hidden');ui.hud.classList.add('hidden');ui.start.classList.remove('hidden');}

function polygon(x,y,r,n,rot=0){ctx.beginPath();for(let i=0;i<n;i++){const a=rot+i*TAU/n;ctx.lineTo(x+Math.cos(a)*r,y+Math.sin(a)*r)}ctx.closePath()}
function draw(){ctx.clearRect(0,0,W,H);const grad=ctx.createRadialGradient(W*.5,H*.45,0,W*.5,H*.45,Math.max(W,H)*.8);grad.addColorStop(0,'#141a35');grad.addColorStop(1,'#050610');ctx.fillStyle=grad;ctx.fillRect(0,0,W,H);
 const ox=shake?rand(-shake,shake):0,oy=shake?rand(-shake,shake):0;ctx.save();ctx.translate(ox,oy);
 for(const s of stars){const x=(s.x*W-elapsed*s.s*2)%W;ctx.globalAlpha=s.a;ctx.fillStyle='#b8dfff';ctx.fillRect(x<0?x+W:x,s.y*H,s.s,s.s)}ctx.globalAlpha=1;
 ctx.strokeStyle='#4d5b8820';ctx.lineWidth=1;const grid=72,px=(-elapsed*7)%grid,py=(-elapsed*4)%grid;for(let x=px;x<W;x+=grid){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=py;y<H;y+=grid){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}
 for(const e of enemies){if(!e.boss||e.specialState!=='windup')continue;const urgency=1-e.specialTimer/2,color=e.specialType==='barrage'?'255,70,155':'255,205,80';ctx.save();ctx.translate(e.x,e.y);ctx.rotate(elapsed*(e.specialType==='barrage'?1.2:-1.6));ctx.globalCompositeOperation='lighter';ctx.shadowBlur=18+urgency*20;ctx.shadowColor=`rgb(${color})`;ctx.lineWidth=3;for(let i=0;i<3;i++){const r=e.r+12+i*15+Math.sin(elapsed*8+i)*4;ctx.strokeStyle=`rgba(${color},${.3+urgency*.5-i*.06})`;ctx.beginPath();ctx.arc(0,0,r,i*.7,Math.PI*1.35+i*.7);ctx.stroke()}ctx.fillStyle=`rgba(${color},${.12+urgency*.18})`;for(let i=0;i<10;i++){const a=i*TAU/10,r=e.r+22+urgency*18;ctx.fillRect(Math.cos(a)*r-2,Math.sin(a)*r-5,4,10)}ctx.restore()}
 for(const e of enemies){if(e.dashState!=='windup')continue;const danger=e.r+player.r,urgency=1-e.dashTimer/(e.boss?2:1.5);ctx.save();ctx.translate(e.x,e.y);ctx.rotate(e.dashAngle);ctx.fillStyle=`rgba(255,35,55,${.16+urgency*.22})`;ctx.strokeStyle=`rgba(255,90,105,${.55+urgency*.4})`;ctx.lineWidth=2;ctx.setLineDash([12,7]);ctx.fillRect(0,-danger,e.dashLength,danger*2);ctx.strokeRect(0,-danger,e.dashLength,danger*2);ctx.setLineDash([]);ctx.fillStyle=`rgba(255,210,215,${.35+urgency*.45})`;ctx.beginPath();ctx.moveTo(e.dashLength,0);ctx.lineTo(e.dashLength-16,-8);ctx.lineTo(e.dashLength-16,8);ctx.closePath();ctx.fill();ctx.restore()}
 for(const g of gems){ctx.save();ctx.translate(g.x,g.y+Math.sin(g.bob)*2);ctx.rotate(g.bob*.25);ctx.shadowBlur=16;ctx.shadowColor='#58eaff';ctx.fillStyle='#71efff';polygon(0,0,g.r,4,Math.PI/4);ctx.fill();ctx.restore()}
 for(const b of bullets){ctx.shadowBlur=14;ctx.shadowColor='#72f5ff';ctx.fillStyle='#d5ffff';ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,TAU);ctx.fill()}ctx.shadowBlur=0;
 for(const b of enemyBullets){ctx.save();ctx.translate(b.x,b.y);ctx.rotate(Math.atan2(b.vy,b.vx));ctx.shadowBlur=14;ctx.shadowColor='#ff203e';ctx.fillStyle='#781529';ctx.globalAlpha=.5;ctx.beginPath();ctx.moveTo(-b.r*3,0);ctx.lineTo(-b.r,2);ctx.lineTo(-b.r,-2);ctx.closePath();ctx.fill();ctx.globalAlpha=1;ctx.fillStyle=b.color;ctx.beginPath();ctx.moveTo(b.r*1.7,0);ctx.lineTo(0,b.r);ctx.lineTo(-b.r*1.25,0);ctx.lineTo(0,-b.r);ctx.closePath();ctx.fill();ctx.fillStyle='#ffd1d6';ctx.beginPath();ctx.moveTo(b.r*.8,0);ctx.lineTo(-b.r*.2,b.r*.3);ctx.lineTo(-b.r*.2,-b.r*.3);ctx.closePath();ctx.fill();ctx.restore()}ctx.shadowBlur=0;for(const b of beams){ctx.globalAlpha=clamp(b.life/.16,0,1);ctx.strokeStyle='#8efcff';ctx.lineWidth=3;ctx.shadowBlur=14;ctx.shadowColor='#64eaff';ctx.beginPath();ctx.moveTo(b.x1,b.y1);ctx.lineTo(b.x2,b.y2);ctx.stroke()}ctx.globalAlpha=1;ctx.shadowBlur=0;
 for(const e of enemies){ctx.save();ctx.translate(e.x,e.y);const a=e.dashState==='windup'||e.dashState==='dashing'?e.dashAngle:Math.atan2(player.y-e.y,player.x-e.x);ctx.rotate(a);if(e.elite){ctx.strokeStyle='#ffe37a';ctx.lineWidth=2;ctx.globalAlpha=.7;ctx.beginPath();ctx.arc(0,0,e.r+7,0,TAU);ctx.stroke()}ctx.shadowBlur=e.hit?25:e.boss?28:10;ctx.shadowColor=e.color;ctx.fillStyle=e.hit?'#fff':e.color;ctx.globalAlpha=.92;if(e.boss){polygon(0,0,e.r,8,elapsed*.18);ctx.fill();ctx.rotate(-elapsed*.36);ctx.fillStyle='#36174b';polygon(0,0,e.r*.68,6);ctx.fill();ctx.fillStyle='#ffb5ff';ctx.beginPath();ctx.arc(0,0,10+Math.sin(elapsed*4)*2,0,TAU)}else if(e.type==='shooter'){polygon(0,0,e.r,4,Math.PI/4);ctx.fill();ctx.fillStyle='#15274d';ctx.beginPath();ctx.arc(0,0,e.r*.48,0,TAU)}else if(e.type==='dasher'){polygon(0,0,e.r,4,Math.PI/4);ctx.fill();ctx.fillStyle='#4a0714';polygon(2,0,e.r*.52,3,0)}else if(e.type==='splitter'){polygon(0,0,e.r,7,elapsed*.2)}else if(e.type==='swift')polygon(0,0,e.r,3,0);else if(e.type==='tank'){polygon(0,0,e.r,6,elapsed*.15);ctx.fill();ctx.fillStyle='#11152a';polygon(0,0,e.r*.55,6,-elapsed*.15)}else polygon(0,0,e.r,5,elapsed*.3);ctx.fill();ctx.restore();const bw=e.boss?100:Math.max(24,e.r*1.8),bh=e.boss?7:4,bx=e.x-bw/2,by=e.y-e.r-13;ctx.fillStyle='#090b14cc';ctx.fillRect(bx-1,by-1,bw+2,bh+2);ctx.fillStyle=e.elite?'#ffd75e':e.boss?'#d963ff':'#ff668e';ctx.fillRect(bx,by,bw*clamp(e.hp/e.maxHp,0,1),bh)}
 for(const p of particles){ctx.globalAlpha=clamp(p.life/.6,0,1);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,p.size,p.size)}ctx.globalAlpha=1;
 if(player&&player.phaseActive){ctx.save();ctx.translate(player.x,player.y);ctx.rotate(elapsed*1.8);ctx.strokeStyle='#76ffe8';ctx.lineWidth=2;ctx.shadowBlur=18;ctx.shadowColor='#54ffe3';ctx.globalAlpha=.65+.2*Math.sin(elapsed*10);polygon(0,0,25,6);ctx.stroke();ctx.restore();ctx.globalAlpha=1;ctx.shadowBlur=0}
 if(player){ctx.save();ctx.translate(player.x,player.y);ctx.rotate(player.angle);ctx.scale(.8,.8);ctx.globalAlpha=player.invuln>0&&Math.floor(player.invuln*16)%2?0.25:1;const thrust=5+Math.sin(elapsed*18)*3;ctx.shadowBlur=18;ctx.shadowColor='#5ff5ff';ctx.fillStyle='#49dff5';ctx.beginPath();ctx.moveTo(-13,-6);ctx.lineTo(-22-thrust,0);ctx.lineTo(-13,6);ctx.closePath();ctx.fill();ctx.shadowBlur=24;ctx.shadowColor='#7b7cff';ctx.fillStyle='#6675d9';ctx.beginPath();ctx.moveTo(8,0);ctx.lineTo(-10,-17);ctx.lineTo(-7,-5);ctx.lineTo(-18,-3);ctx.lineTo(-13,0);ctx.lineTo(-18,3);ctx.lineTo(-7,5);ctx.lineTo(-10,17);ctx.closePath();ctx.fill();ctx.fillStyle='#d7faff';ctx.beginPath();ctx.moveTo(18,0);ctx.lineTo(-10,-8);ctx.lineTo(-13,0);ctx.lineTo(-10,8);ctx.closePath();ctx.fill();ctx.fillStyle='#17213f';ctx.beginPath();ctx.ellipse(4,0,7,4,0,0,TAU);ctx.fill();ctx.fillStyle='#7cffff';ctx.beginPath();ctx.arc(5,0,2.5,0,TAU);ctx.fill();ctx.restore()}
 for(const t of texts){ctx.globalAlpha=clamp(t.life/(t.big?1.2:t.playerDamage?.75:t.critical?.7:.45),0,1);ctx.fillStyle=t.big?'#f1c6ff':t.playerDamage?'#ff4968':t.critical?'#ffe575':'#fff';ctx.font=t.big?'900 22px sans-serif':t.playerDamage?'900 18px sans-serif':t.critical?'900 14px sans-serif':'700 12px sans-serif';ctx.textAlign='center';ctx.fillText(t.text,t.x,t.y)}ctx.globalAlpha=1;ctx.restore();if(flash){ctx.fillStyle=`rgba(255,60,100,${flash*.7})`;ctx.fillRect(0,0,W,H)}}

const MUSIC={menu:'audio/menu.mp3',battle:'audio/battle.mp3',boss:'audio/boss.mp3',victory:'audio/victory.mp3'};
const musicToggle=$('#music-toggle'),bgm=new Audio();
let musicEnabled=localStorage.getItem('star-survivor-music')!=='off',musicUnlocked=false,desiredMusic='menu';
bgm.preload='auto';bgm.volume=.22;
function updateMusicToggle(){musicToggle.textContent=musicEnabled?'♫':'♪';musicToggle.classList.toggle('muted',!musicEnabled);musicToggle.setAttribute('aria-pressed',String(musicEnabled));musicToggle.setAttribute('aria-label',musicEnabled?'關閉背景音樂':'開啟背景音樂');musicToggle.title=`背景音樂：${musicEnabled?'開啟':'關閉'}`}
function playDesiredMusic(){if(!musicEnabled||!musicUnlocked)return;const src=MUSIC[desiredMusic];if(!bgm.src.endsWith(src)){bgm.pause();bgm.src=src;bgm.currentTime=0}bgm.loop=desiredMusic!=='victory';bgm.play().catch(()=>{})}
function setMusic(name){desiredMusic=name;if(name==='battle'||name==='menu')musicUnlocked=true;playDesiredMusic()}
function unlockMusic(){if(musicUnlocked)return;musicUnlocked=true;playDesiredMusic()}
function toggleMusic(e){e.stopPropagation();musicUnlocked=true;musicEnabled=!musicEnabled;localStorage.setItem('star-survivor-music',musicEnabled?'on':'off');updateMusicToggle();if(musicEnabled)playDesiredMusic();else bgm.pause()}
bgm.addEventListener('ended',()=>{if(desiredMusic==='victory'){desiredMusic='menu';playDesiredMusic()}});
musicToggle.addEventListener('click',toggleMusic);document.addEventListener('pointerdown',unlockMusic,{once:true});updateMusicToggle();
let audioCtx;function beep(freq,duration,type='sine',volume=.03){try{audioCtx??=new (AudioContext||webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(volume,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+duration);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+duration)}catch{}}
function togglePause(){if(state==='playing'){state='paused';ui.pause.classList.remove('hidden')}else if(state==='paused'){state='playing';ui.pause.classList.add('hidden');last=performance.now()}}
addEventListener('keydown',e=>{keys[e.code]=true;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();if(e.code==='Escape'&&!ui.guide.classList.contains('hidden'))ui.guide.classList.add('hidden');else if((e.code==='Escape'||e.code==='KeyP')&&(state==='playing'||state==='paused'))togglePause()});addEventListener('keyup',e=>keys[e.code]=false);
const floatingJoystick=$('#floating-joystick'),floatingStick=$('#floating-stick');
function moveTouch(e){if(e.pointerId!==touch.id||state!=='playing')return;e.preventDefault();const dx=e.clientX-touch.startX,dy=e.clientY-touch.startY,d=Math.hypot(dx,dy),max=38,visual=Math.min(d,max),vx=d?dx/d:0,vy=d?dy/d:0;floatingStick.style.transform=`translate(${vx*visual}px,${vy*visual}px)`;if(d<=6){touch.x=touch.y=0}else{touch.x=vx;touch.y=vy}}
function resetTouch(e){if(e&&e.pointerId!==touch.id)return;touch.active=false;touch.id=null;touch.x=touch.y=0;floatingStick.style.transform='translate(0,0)';floatingJoystick.classList.add('hidden')}
canvas.addEventListener('pointerdown',e=>{if(state!=='playing'||e.pointerType==='mouse'||touch.active)return;e.preventDefault();const rect=shell.getBoundingClientRect();touch.active=true;touch.id=e.pointerId;touch.startX=e.clientX;touch.startY=e.clientY;touch.x=touch.y=0;floatingJoystick.style.left=`${e.clientX-rect.left}px`;floatingJoystick.style.top=`${e.clientY-rect.top}px`;floatingJoystick.classList.remove('hidden');canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',moveTouch);canvas.addEventListener('pointerup',resetTouch);canvas.addEventListener('pointercancel',resetTouch);canvas.addEventListener('lostpointercapture',resetTouch);
document.querySelectorAll('[data-weapon]').forEach(button=>button.onclick=()=>{selectedWeapon=button.dataset.weapon;document.querySelectorAll('[data-weapon]').forEach(b=>b.classList.toggle('selected',b===button));beep(420,.05,'sine',.025)});document.querySelectorAll('.home-button').forEach(button=>button.onclick=goHome);$('#open-guide').onclick=()=>ui.guide.classList.remove('hidden');$('#close-guide').onclick=()=>ui.guide.classList.add('hidden');$('#start').onclick=startGame;$('#restart').onclick=startGame;$('#copy-report').onclick=copyTestReport;$('#pause').onclick=togglePause;$('#resume').onclick=togglePause;
function loop(now){const dt=Math.min((now-last)/1000,.033)||0;last=now;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
